import { Link, useNavigate } from 'react-router-dom';
import { BookOpenIcon } from '@heroicons/react/24/outline';
import { useLanguage } from '../context/LanguageContext';
import { useLocalStorage } from '../hooks/useLocalStorage';
import { useQuestions } from '../hooks/useQuestions';
import { getLessonsForCategory } from '../data/lessons';
import { Mistakes, getUniqueMistakes } from '../utils/mistakes';
import Header from '../components/Header';

function calculateStats(mistakes: Mistakes) {
  const unique = getUniqueMistakes(Object.values(mistakes).flat()); const byCategory = unique.reduce<Record<string,number>>((counts,mistake)=>{counts[mistake.category]=(counts[mistake.category]||0)+1;return counts;},{});
  return { totalMistakes:unique.length, mistakesByCategory:byCategory, reviewMinutes:unique.length?Math.max(3,Math.ceil(unique.length*0.75)):0 };
}

export default function MistakesScreen() {
  const navigate=useNavigate(); const { t }=useLanguage(); const { getCategories }=useQuestions(); const [mistakes]=useLocalStorage<Mistakes>('quizMistakes',{}); const stats=calculateStats(mistakes);
  const categories=getCategories().map((id)=>({id,wrongCount:stats.mistakesByCategory[id]||0,lesson:getLessonsForCategory(id)[0]})).filter((item)=>item.wrongCount>0).sort((a,b)=>b.wrongCount-a.wrongCount);
  const play=(categoryId?:string)=>{const source=categoryId?mistakes[categoryId]||[]:Object.values(mistakes).flat();const unique=getUniqueMistakes(source);if(!unique.length)return;sessionStorage.setItem('currentMistakes',JSON.stringify(unique));navigate(categoryId?`/quiz?mode=mistakes&category=${encodeURIComponent(categoryId)}`:'/quiz?mode=mistakes');};
  return <div className="pb-24 pt-4"><Header title={t('mistakesScreen.title')} /><div className="space-y-8 px-4"><div className="grid grid-cols-3 gap-2 sm:gap-4"><div className="rounded-2xl border border-base-300 bg-base-100 p-3 text-center"><div className="text-2xl font-bold text-primary">{stats.totalMistakes}</div><div className="text-xs text-base-content/60">Unresolved</div></div><div className="rounded-2xl border border-base-300 bg-base-100 p-3 text-center"><div className="text-2xl font-bold text-primary">{categories.length}</div><div className="text-xs text-base-content/60">Areas</div></div><div className="rounded-2xl border border-base-300 bg-base-100 p-3 text-center"><div className="text-2xl font-bold text-primary">{stats.reviewMinutes}m</div><div className="text-xs text-base-content/60">Estimate</div></div></div>{stats.totalMistakes>0?<><button type="button" onClick={()=>play()} className="btn btn-primary w-full">Repair all {stats.totalMistakes} mistakes</button><section><p className="text-xs font-semibold uppercase tracking-wider text-error">Repair priority</p><h2 className="mt-1 text-xl font-bold">Retrieve or relearn</h2><div className="mt-4 space-y-4">{categories.map((category,index)=><article key={category.id} className="rounded-2xl border border-base-300 bg-base-100 p-4"><div className="flex items-start justify-between"><div><div className="flex gap-2"><h3 className="font-bold">{category.id.replace(/_/g,' ')}</h3>{index===0&&categories.length>1&&<span className="badge badge-error badge-outline badge-sm">Top priority</span>}</div><p className="mt-1 text-sm text-base-content/65">{category.wrongCount} unresolved</p></div><span className="rounded-full bg-error/10 px-3 py-1 text-sm font-semibold text-error">{category.wrongCount}</span></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>play(category.id)} className="btn btn-primary btn-sm">Review mistakes</button>{category.lesson&&<Link to={`/lessons/${category.lesson.id}`} className="btn btn-ghost btn-sm"><BookOpenIcon className="h-4 w-4" />Relearn</Link>}</div></article>)}</div></section></>:<div className="rounded-3xl bg-success/5 p-8 text-center"><div className="text-3xl">✓</div><h2 className="mt-2 text-xl font-bold">Nothing unresolved</h2><p className="mt-2 text-sm text-base-content/65">A future recall miss will return here for immediate repair.</p><Link to="/categories" className="btn btn-primary btn-sm mt-5">Keep learning</Link></div>}</div></div>;
}
