import { useState, useEffect, useRef } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { InformationCircleIcon } from '@heroicons/react/24/outline';
import { useQuiz } from '../context/QuizContext';
import { useQuestions } from '../hooks/useQuestions';
import { Question } from '../types/question';
import { useLocalStorage } from '../hooks/useLocalStorage';
import { useLanguage } from '../context/LanguageContext';
import { normalizeUrl } from '../utils/helpers';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import MultipleChoiceDisplay from '../components/question-types/MultipleChoiceDisplay';
import TrueFalseDisplay from '../components/question-types/TrueFalseDisplay';
import FillInTheBlankDisplay from '../components/question-types/FillInTheBlankDisplay';
import Header from '../components/Header';
import soundManager from '../utils/soundManager';
import { useAchievements } from '../hooks/useAchievements';
import { LearningState, getDueQuestionIds, recordQuestionAttempt } from '../utils/learningState';

interface Progress { [key:string]: { [key:string]: { completed:number; correct:number } } }
interface Mistake { questionId:string; category:string; difficulty:string; selectedAnswer:string|string[]; timestamp:number }
const shuffle=<T,>(items:T[])=>{const result=[...items];for(let index=result.length-1;index>0;index-=1){const swap=Math.floor(Math.random()*(index+1));[result[index],result[swap]]=[result[swap],result[index]];}return result;};

export default function QuizScreen() {
  const {t}=useLanguage(); const navigate=useNavigate(); const [searchParams]=useSearchParams(); const {allQuestions,getQuestionsByCategory,getRandomQuestions}=useQuestions(); const {currentQuiz,setCurrentQuiz}=useQuiz(); const [progress,setProgress]=useLocalStorage<Progress>('quizProgress',{}); const [mistakes,setMistakes]=useLocalStorage<Record<string,Mistake[]>>('quizMistakes',{}); const [maxStreak,setMaxStreak]=useLocalStorage<number>('maxStreak',0); const [soundEnabled]=useLocalStorage<boolean>('soundEnabled',true); const [learningState,setLearningState]=useLocalStorage<LearningState>('questionLearningState',{}); const {updateProgress}=useAchievements();
  const [currentQuestionIndex,setCurrentQuestionIndex]=useState(0); const [selectedAnswer,setSelectedAnswer]=useState<string|string[]|null>(null); const [showExplanation,setShowExplanation]=useState(false); const [showAnswerResult,setShowAnswerResult]=useState(false); const [answers,setAnswers]=useState<Record<string,string|string[]>>({}); const [questions,setQuestions]=useState<Question[]>([]); const [currentStreak,setCurrentStreak]=useState(0); const [isLoading,setIsLoading]=useState(true); const [incorrectAnswers,setIncorrectAnswers]=useState<Set<string>>(new Set()); const [questionStartTime,setQuestionStartTime]=useState(Date.now()); const reviewQuestionIds=useRef<string[]|null>(null);
  const isMistakesMode=searchParams.get('mode')==='mistakes'; const isReviewMode=searchParams.get('mode')==='review'; const isPlayAllMode=window.location.pathname==='/play-all';

  useEffect(()=>{setIsLoading(true);if(isPlayAllMode){setCurrentQuiz({...currentQuiz,playAllMode:true,currentStreak:0});setQuestions(getRandomQuestions(1));setCurrentStreak(0);}else if(isReviewMode){if(reviewQuestionIds.current===null)reviewQuestionIds.current=getDueQuestionIds(learningState);const due=new Set(reviewQuestionIds.current);setQuestions(allQuestions.filter((question)=>due.has(question.id)).slice(0,12));}else if(isMistakesMode){const stored=sessionStorage.getItem('currentMistakes');if(!stored){navigate('/mistakes');return;}const selected=JSON.parse(stored) as Mistake[];const category=searchParams.get('category');const filtered=category?selected.filter((mistake)=>mistake.category===category):selected;setQuestions(filtered.map((mistake)=>getQuestionsByCategory(mistake.category).find((question)=>question.id===mistake.questionId)).filter((question):question is Question=>!!question));}else{const filtered=getQuestionsByCategory(currentQuiz.category||'').filter((question)=>question.difficulty===currentQuiz.difficulty);setQuestions(shuffle(filtered).slice(0,10));}setIsLoading(false);},[currentQuiz.category,currentQuiz.difficulty,isMistakesMode,isReviewMode,isPlayAllMode,navigate,setCurrentQuiz,allQuestions]);
  useEffect(()=>{if(!isLoading&&questions.length===0)navigate(isMistakesMode?'/mistakes':isReviewMode?'/dashboard':'/categories');},[isLoading,questions,navigate,isMistakesMode,isReviewMode]);
  useEffect(()=>setQuestionStartTime(Date.now()),[currentQuestionIndex,questions]);

  const isAnswerCorrect=(question:Question,answer:string|string[])=>{if(!answer)return false;const isImage=(option:string)=>option.startsWith('http');if(question.type==='multiple-choice'){const normalize=(value:string)=>isImage(value)?normalizeUrl(value):value.toLowerCase();if(Array.isArray(question.correctAnswer)){if(!Array.isArray(answer))return false;const expected=new Set(question.correctAnswer.map(normalize));const actual=new Set(answer.map(normalize));return expected.size===actual.size&&[...expected].every((value)=>actual.has(value));}return normalize(answer.toString())===normalize(question.correctAnswer);}if(question.type==='true-false')return answer.toString().toLowerCase()===String(question.correctAnswer).toLowerCase();if(question.type==='fill-in-the-blank')return answer.toString().trim().toLowerCase()===question.correctAnswer.trim().toLowerCase();return false;};

  const currentQuestion=questions[currentQuestionIndex];
  const persistMistake=(answer:string|string[])=>{if(isPlayAllMode||isMistakesMode)return;const key=currentQuestion.category;const entry:Mistake={questionId:currentQuestion.id,category:currentQuestion.category,difficulty:currentQuestion.difficulty,selectedAnswer:answer,timestamp:Date.now()};const existing=mistakes[key]||[];setMistakes({...mistakes,[key]:[...existing.filter((item)=>!(item.questionId===entry.questionId&&item.category===entry.category&&item.difficulty===entry.difficulty)),entry]});};

  const handleNext=(answerOverride?:string|string[])=>{const finalAnswer=answerOverride||selectedAnswer;if(!finalAnswer||(Array.isArray(finalAnswer)&&!finalAnswer.length)||!currentQuestion)return;setShowExplanation(false);setShowAnswerResult(false);const correct=isAnswerCorrect(currentQuestion,finalAnswer);const timeToAnswerSec=Math.max(0,Math.round((Date.now()-questionStartTime)/1000));setLearningState((state)=>recordQuestionAttempt(state,currentQuestion.id,correct,{responseTimeSec:timeToAnswerSec}));const finalIncorrect=new Set(incorrectAnswers);if(!correct&&!isPlayAllMode&&!isMistakesMode){finalIncorrect.add(currentQuestion.id);setIncorrectAnswers(finalIncorrect);}
    if(isPlayAllMode){if(correct){const streak=currentStreak+1;setCurrentStreak(streak);updateProgress({questionsAnswered:1,correctAnswers:1,streak,timeToAnswerSec});if(soundEnabled&&(streak===5||streak===10||streak===15))soundManager.play('streak');if(streak>maxStreak)setMaxStreak(streak);setQuestions(getRandomQuestions(1));setCurrentQuestionIndex(0);setSelectedAnswer(null);setCurrentQuiz({...currentQuiz,currentStreak:streak,maxStreak:Math.max(streak,maxStreak)});}else{updateProgress({questionsAnswered:1,correctAnswers:0,streak:currentStreak,timeToAnswerSec});if(soundEnabled&&currentStreak>0)soundManager.play('levelComplete');navigate('/results',{state:{playAllMode:true,finalStreak:currentStreak,maxStreak:Math.max(currentStreak,maxStreak),lastQuestion:currentQuestion,lastAnswer:finalAnswer}});}return;}
    if(isReviewMode){updateProgress({questionsAnswered:1,correctAnswers:correct?1:0,timeToAnswerSec});if(currentQuestionIndex<questions.length-1){setCurrentQuestionIndex((value)=>value+1);setSelectedAnswer(null);}else navigate('/dashboard');return;}
    if(isMistakesMode){if(correct){const updated={...mistakes};let repaired=false;Object.keys(updated).forEach((category)=>{const before=updated[category];const after=before.filter((item)=>!(item.questionId===currentQuestion.id&&item.category===currentQuestion.category&&item.difficulty===currentQuestion.difficulty));if(after.length!==before.length){repaired=true;if(after.length)updated[category]=after;else delete updated[category];}});if(repaired)setMistakes(updated);updateProgress({questionsAnswered:1,correctAnswers:1,mistakesReviewed:repaired?1:0,timeToAnswerSec});}else updateProgress({questionsAnswered:1,correctAnswers:0,timeToAnswerSec});if(currentQuestionIndex<questions.length-1){setCurrentQuestionIndex((value)=>value+1);setSelectedAnswer(null);}else navigate('/mistakes');return;}
    const category=currentQuiz.category||'';const difficulty=currentQuiz.difficulty||'';const categoryProgress=progress[category]||{};const difficultyProgress=categoryProgress[difficulty]||{completed:0,correct:0};setProgress({...progress,[category]:{...categoryProgress,[difficulty]:{completed:difficultyProgress.completed+1,correct:difficultyProgress.correct+(correct?1:0)}}});updateProgress({questionsAnswered:1,correctAnswers:correct?1:0,timeToAnswerSec});
    if(currentQuestionIndex<questions.length-1){setCurrentQuestionIndex((value)=>value+1);setSelectedAnswer(null);return;}const finalAnswers={...answers,[currentQuestion.id]:finalAnswer};const score=Object.entries(finalAnswers).reduce((sum,[questionId,answer])=>{const question=questions.find((item)=>item.id===questionId);return sum+(question&&isAnswerCorrect(question,answer)?1:0);},0);if(score===questions.length&&questions.length>=10)updateProgress({isPerfectScore:true});if(soundEnabled)soundManager.play('levelComplete');navigate('/results',{state:{score,total:questions.length,answers:finalAnswers,questions,incorrectQuestionIds:Array.from(finalIncorrect)}});
  };

  const handleAnswerSelect=(answer:string|string[])=>{if(showAnswerResult)return;if(Array.isArray(currentQuestion.correctAnswer)){setSelectedAnswer(answer);return;}setSelectedAnswer(answer);setShowAnswerResult(true);setAnswers((previous)=>({...previous,[currentQuestion.id]:answer}));const correct=isAnswerCorrect(currentQuestion,answer);if(soundEnabled)soundManager.play(correct?'correct':'incorrect');if(!correct)persistMistake(answer);window.setTimeout(()=>{if(correct)handleNext(answer);else setShowExplanation(true);},2000);};
  const handleMultiSubmit=()=>{if(showAnswerResult||!selectedAnswer)return;setShowAnswerResult(true);setAnswers((previous)=>({...previous,[currentQuestion.id]:selectedAnswer}));const correct=isAnswerCorrect(currentQuestion,selectedAnswer);if(soundEnabled)soundManager.play(correct?'correct':'incorrect');if(!correct)persistMistake(selectedAnswer);window.setTimeout(()=>{if(correct)handleNext(selectedAnswer);else setShowExplanation(true);},2000);};

  if(isLoading||!currentQuestion)return <div>{t('quizScreen.loading')}</div>;
  const renderQuestion=()=>{if(currentQuestion.type==='multiple-choice')return <MultipleChoiceDisplay question={currentQuestion} selectedAnswer={selectedAnswer} onAnswerSelect={handleAnswerSelect} showResult={showAnswerResult} onSubmit={Array.isArray(currentQuestion.correctAnswer)?handleMultiSubmit:undefined} />;if(currentQuestion.type==='true-false')return <TrueFalseDisplay question={currentQuestion} selectedAnswer={typeof selectedAnswer==='string'?selectedAnswer:null} onAnswerSelect={handleAnswerSelect} showResult={showAnswerResult} />;if(currentQuestion.type==='fill-in-the-blank')return <FillInTheBlankDisplay question={currentQuestion} selectedAnswer={typeof selectedAnswer==='string'?selectedAnswer:null} onAnswerSelect={handleAnswerSelect} showResult={showAnswerResult} />;return <p>{t('quizScreen.unsupportedQuestionType')}</p>;};
  return <div className="min-h-screen bg-base-200 pb-20 pt-4"><Header title={isPlayAllMode?t('dashboard.playAll'):isReviewMode?t('quizScreen.reviewSession'):isMistakesMode?t('mistakesScreen.title'):`${currentQuiz.category?currentQuiz.category.replace(/_/g,' '):'Quiz'} ${currentQuiz.difficulty?`- ${currentQuiz.difficulty}`:''}`} /><div className="mb-6 flex justify-center"><div className="flex h-20 w-20 items-center justify-center rounded-full bg-gradient-to-br from-primary to-secondary shadow-lg"><span className="text-3xl font-bold text-primary-content">{currentQuestionIndex+1}</span></div></div><div className="px-4"><div className="relative rounded-2xl border-2 border-b-4 border-base-300 bg-base-100 p-6 shadow-lg"><button onClick={()=>setShowExplanation(true)} className="absolute right-4 top-4 rounded-full p-2 hover:bg-base-200" aria-label={t('quizScreen.showExplanation')}><InformationCircleIcon className="h-6 w-6 text-base-content/40" /></button>{currentQuestion.imageUrl&&<img src={currentQuestion.imageUrl} alt="Question" className="mb-4 h-auto w-full rounded-t-2xl object-cover" />}<h2 className="mb-6 pr-10 text-xl font-medium">{currentQuestion.question}</h2>{renderQuestion()}</div></div>{showExplanation&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-base-200/50 p-4 backdrop-blur-sm"><div className="w-full max-w-md overflow-hidden rounded-2xl border-2 border-b-4 border-base-300 bg-base-100 shadow-xl"><div className="p-6"><h3 className="mb-4 text-xl font-bold">{t('resultsScreen.explanation')}</h3><div className="prose max-w-none rounded-xl bg-base-200/50 p-4 text-base-content/80"><ReactMarkdown remarkPlugins={[remarkGfm]}>{currentQuestion.explanation}</ReactMarkdown></div></div><div className="flex justify-end bg-base-200 px-6 py-4"><button onClick={()=>{setShowExplanation(false);handleNext(selectedAnswer||undefined);}} className="btn btn-primary">{t('quizScreen.understood')}</button></div></div></div>}</div>;
}
