import { useMemo, useState } from 'react';
export default function BayesLab(){
 const [prevalence,setPrevalence]=useState(5);const [sensitivity,setSensitivity]=useState(90);const [falsePositive,setFalsePositive]=useState(10);const [positivesOnly,setPositivesOnly]=useState(false);
 const counts=useMemo(()=>{const total=1000;const condition=total*prevalence/100;const healthy=total-condition;const tp=condition*sensitivity/100;const fn=condition-tp;const fp=healthy*falsePositive/100;const tn=healthy-fp;return{tp,fn,fp,tn,posterior:tp/Math.max(1,tp+fp)*100};},[prevalence,sensitivity,falsePositive]);
 const cells=Array.from({length:100},(_,i)=>{const p=i*10;if(p<counts.tp)return'tp';if(p<counts.tp+counts.fp)return'fp';if(p<counts.tp+counts.fp+counts.fn)return'fn';return'tn';});const visible=positivesOnly?cells.filter((x)=>x==='tp'||x==='fp'):cells;const styles:Record<string,string>={tp:'bg-success',fp:'bg-warning',fn:'bg-error/60',tn:'bg-base-content/15'};
 return <div className="space-y-5"><div className="grid gap-4 lg:grid-cols-[1fr_.75fr]"><div className="rounded-3xl bg-base-200/70 p-4"><div className="grid grid-cols-10 gap-1.5">{visible.map((cell,i)=><div key={`${cell}-${i}`} className={`aspect-square rounded-sm ${styles[cell]}`} />)}</div></div><div className="rounded-3xl border border-primary/20 bg-primary/5 p-5 text-center"><div className="text-xs font-bold uppercase text-primary">After a positive result</div><div className="mt-2 text-5xl font-black">{counts.posterior.toFixed(1)}%</div><button className="btn btn-ghost btn-sm mt-4" onClick={()=>setPositivesOnly((v)=>!v)}>{positivesOnly?'Show everyone':'Isolate positives'}</button></div></div>
 <div className="grid gap-4 sm:grid-cols-3"><label className="space-y-2"><span className="flex justify-between text-sm"><span>Prior prevalence</span><span>{prevalence}%</span></span><input className="range range-primary range-sm" type="range" min="1" max="50" value={prevalence} onChange={(e)=>setPrevalence(Number(e.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm"><span>Sensitivity</span><span>{sensitivity}%</span></span><input className="range range-secondary range-sm" type="range" min="50" max="100" value={sensitivity} onChange={(e)=>setSensitivity(Number(e.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm"><span>False-positive rate</span><span>{falsePositive}%</span></span><input className="range range-accent range-sm" type="range" min="1" max="35" value={falsePositive} onChange={(e)=>setFalsePositive(Number(e.target.value))} /></label></div>
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['True +',counts.tp],['False +',counts.fp],['False −',counts.fn],['True −',counts.tn]].map(([l,v])=><div key={String(l)} className="rounded-2xl bg-base-200/70 p-3 text-center"><div className="text-xs">{l}</div><div className="text-xl font-black">{Math.round(Number(v))}</div><div className="text-[11px]">per 1,000</div></div>)}</div><p className="text-xs leading-5 text-base-content/60">Assumes stable test characteristics and a relevant prior population. Real diagnosis needs context.</p></div>;
}
