import { useMemo, useState } from 'react';

export default function CompoundGrowthLab() {
  const [principal, setPrincipal] = useState(1000); const [monthly, setMonthly] = useState(100); const [annualRate, setAnnualRate] = useState(7); const [inflation, setInflation] = useState(3); const [years, setYears] = useState(20);
  const series = useMemo(() => { const monthlyRate = annualRate / 100 / 12; let balance = principal; let contributed = principal; const points = [{ year: 0, balance, contributed, real: balance }]; for (let month = 1; month <= years * 12; month += 1) { balance *= 1 + monthlyRate; balance += monthly; contributed += monthly; if (month % 12 === 0) { const year = month / 12; points.push({ year, balance, contributed, real: balance / ((1 + inflation / 100) ** year) }); } } return points; }, [principal, monthly, annualRate, inflation, years]);
  const final = series[series.length - 1]; const maximum = Math.max(...series.map((point) => point.balance), 1); const x = (year: number) => 6 + year / Math.max(1, years) * 88; const y = (value: number) => 92 - value / maximum * 78;
  const balancePoints = series.map((point) => `${x(point.year)},${y(point.balance)}`).join(' '); const contributionPoints = series.map((point) => `${x(point.year)},${y(point.contributed)}`).join(' '); const realPoints = series.map((point) => `${x(point.year)},${y(point.real)}`).join(' ');
  return <div className="space-y-5">
    <div className="rounded-3xl bg-slate-950 p-4 sm:p-6"><svg viewBox="0 0 100 100" className="h-64 w-full" role="img" aria-label="Contributions, compound balance, and inflation-adjusted purchasing power">{[25, 50, 75].map((value) => <line key={value} x1="6" x2="94" y1={92 - value * 0.78} y2={92 - value * 0.78} className="stroke-slate-800" strokeWidth="0.4" />)}<polyline points={contributionPoints} fill="none" className="stroke-amber-300" strokeWidth="1.7" /><polyline points={realPoints} fill="none" className="stroke-fuchsia-300" strokeWidth="1.8" /><polyline points={balancePoints} fill="none" className="stroke-cyan-300" strokeWidth="2.5" /><text x="61" y="10" className="fill-cyan-300 text-[3.7px]">nominal balance</text><text x="61" y="16" className="fill-fuchsia-300 text-[3.7px]">inflation-adjusted</text><text x="61" y="22" className="fill-amber-300 text-[3.7px]">money contributed</text><text x="78" y="98" className="fill-slate-500 text-[3px]">years →</text></svg></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Starting</span><span>${principal}</span></span><input className="range range-primary range-sm" type="range" min="0" max="10000" step="250" value={principal} onChange={(event) => setPrincipal(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Monthly</span><span>${monthly}</span></span><input className="range range-secondary range-sm" type="range" min="0" max="1000" step="25" value={monthly} onChange={(event) => setMonthly(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Annual return</span><span>{annualRate}%</span></span><input className="range range-accent range-sm" type="range" min="0" max="15" step="0.5" value={annualRate} onChange={(event) => setAnnualRate(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Inflation</span><span>{inflation}%</span></span><input className="range range-warning range-sm" type="range" min="0" max="10" step="0.5" value={inflation} onChange={(event) => setInflation(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Time</span><span>{years}y</span></span><input className="range range-info range-sm" type="range" min="1" max="40" value={years} onChange={(event) => setYears(Number(event.target.value))} /></label></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Contributed</div><div className="mt-1 font-black">${Math.round(final.contributed).toLocaleString()}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Nominal balance</div><div className="mt-1 font-black">${Math.round(final.balance).toLocaleString()}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Growth above deposits</div><div className="mt-1 font-black">${Math.round(final.balance - final.contributed).toLocaleString()}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Real purchasing power</div><div className="mt-1 font-black">${Math.round(final.real).toLocaleString()}</div></div></div>
    <div className="flex flex-wrap gap-2"><button type="button" className="btn btn-outline btn-sm" onClick={() => { setPrincipal(0); setMonthly(200); setAnnualRate(7); setInflation(3); setYears(30); }}>Steady saver</button><button type="button" className="btn btn-outline btn-sm" onClick={() => { setPrincipal(5000); setMonthly(0); setAnnualRate(7); setInflation(3); setYears(30); }}>One deposit</button><button type="button" className="btn btn-outline btn-sm" onClick={() => { setAnnualRate(4); setInflation(5); }}>Inflation pressure</button></div>
    <p className="text-xs leading-5 text-base-content/60">This assumes a constant return, monthly deposits, no fees, no taxes, and smooth inflation. Real investments fluctuate and can lose value. The lab teaches accounting relationships, not financial advice.</p>
  </div>;
}
