import { useEffect, useMemo, useState } from 'react';
import usePrefersReducedMotion from '../../hooks/usePrefersReducedMotion';
type Point={a:number;b:number};
export default function EquilibriumLab(){
  const [forward,setForward]=useState(0.45);const [reverse,setReverse]=useState(0.25);const [initialA,setInitialA]=useState(0.9);const [step,setStep]=useState(0);const [playing,setPlaying]=useState(false);const prefersReducedMotion=usePrefersReducedMotion();
  const series=useMemo<Point[]>(()=>{const values:Point[]=[{a:initialA,b:1-initialA}];for(let i=1;i<=120;i+=1){const p=values[i-1];const change=(reverse*p.b-forward*p.a)*0.08;const a=Math.max(0,Math.min(1,p.a+change));values.push({a,b:1-a});}return values;},[forward,reverse,initialA]);
  const current=series[Math.min(step,120)];const equilibriumA=reverse/(forward+reverse);const aPoints=series.map((p,i)=>`${i/1.2},${100-p.a*100}`).join(' ');const bPoints=series.map((p,i)=>`${i/1.2},${100-p.b*100}`).join(' ');
  useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setStep((value)=>{if(value>=120){setPlaying(false);return 120;}return value+1;}),45);return()=>window.clearInterval(timer);},[playing]);
  useEffect(()=>{if(prefersReducedMotion&&playing){setPlaying(false);setStep(120);}},[prefersReducedMotion,playing]);
  const reset=()=>{setPlaying(false);setStep(0);};const update=(setter:(value:number)=>void,value:number)=>{setter(value);reset();};const run=()=>{setStep(prefersReducedMotion?120:0);setPlaying(!prefersReducedMotion);};
  return <div className="min-w-0 max-w-full space-y-5 overflow-x-hidden"><div className="lab-grid lab-grid-wide"><div className="rounded-3xl bg-slate-950 p-4"><svg viewBox="0 0 100 104" className="h-56 w-full" role="img" aria-label="A and B approaching equilibrium"><polyline points={aPoints} fill="none" className="stroke-cyan-300" strokeWidth="2" /><polyline points={bPoints} fill="none" className="stroke-fuchsia-300" strokeWidth="2" /><line x1={step/1.2} x2={step/1.2} y1="0" y2="100" className="stroke-white/50" strokeDasharray="2 2" /><text x="2" y="8" className="fill-cyan-300 text-[4px]">A</text><text x="8" y="8" className="fill-fuchsia-300 text-[4px]">B</text></svg></div><div className="rounded-3xl bg-base-200/70 p-4"><div className="grid grid-cols-5 gap-2">{Array.from({length:40},(_,i)=><div key={i} className={`aspect-square rounded-full ${i<Math.round(current.a*40)?'bg-primary':'bg-secondary'}`} />)}</div><div className="mt-4 grid grid-cols-2 gap-2 text-center"><div className="rounded-xl bg-primary/10 p-2"><div className="text-xs">A</div><div className="text-xl font-black">{Math.round(current.a*100)}%</div></div><div className="rounded-xl bg-secondary/10 p-2"><div className="text-xs">B</div><div className="text-xl font-black">{Math.round(current.b*100)}%</div></div></div></div></div>
    <div className="lab-grid lab-grid-medium"><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>A → B rate</span><span>{forward.toFixed(2)}</span></span><input className="range range-primary range-sm" type="range" min="0.05" max="0.9" step="0.05" value={forward} onChange={(e)=>update(setForward,Number(e.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>B → A rate</span><span>{reverse.toFixed(2)}</span></span><input className="range range-secondary range-sm" type="range" min="0.05" max="0.9" step="0.05" value={reverse} onChange={(e)=>update(setReverse,Number(e.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>Starting A</span><span>{Math.round(initialA*100)}%</span></span><input className="range range-accent range-sm" type="range" min="0.05" max="0.95" step="0.05" value={initialA} onChange={(e)=>update(setInitialA,Number(e.target.value))} /></label></div>
    <div className="lab-grid lab-grid-medium">{[['Equilibrium A',`${Math.round(equilibriumA*100)}%`],['Forward flux',(forward*current.a).toFixed(3)],['Reverse flux',(reverse*current.b).toFixed(3)]].map(([label,value])=><div key={label} className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">{label}</div><div className="mt-1 text-xl font-black">{value}</div></div>)}</div><div className="flex gap-2"><button type="button" className="btn btn-primary btn-sm" onClick={run}>{prefersReducedMotion?'Show equilibrium':playing?'Restart':'Run reaction'}</button><button type="button" className="btn btn-ghost btn-sm" onClick={reset}>Reset</button></div><p className="text-xs leading-5 text-base-content/60">A closed, mass-conserving first-order toy system. Equilibrium means equal opposing fluxes, not stopped molecular change.</p></div>;
}
