import { useState } from 'react';
import { ArrowTopRightOnSquareIcon, CheckCircleIcon, LightBulbIcon, XCircleIcon } from '@heroicons/react/24/outline';
import { LessonBlock } from '../../types/lesson';
import { LessonCheckpointResult } from '../../utils/lessonProgress';
import LessonVisual from './LessonVisual';

const getYouTubeEmbedUrl = (url: string, startSeconds?: number) => { const match = url.match(/(?:v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/); return match ? `https://www.youtube.com/embed/${match[1]}${startSeconds ? `?start=${startSeconds}` : ''}` : undefined; };

export default function LessonBlockView({ block, checkpointResult, reflectionValue = '', onCheckpoint, onReflection }: { block: LessonBlock; checkpointResult?: LessonCheckpointResult; reflectionValue?: string; onCheckpoint: (answer: string, correct: boolean) => void; onReflection: (value: string) => void }) {
  const [selected, setSelected] = useState(checkpointResult?.selectedAnswer || ''); const [reflection, setReflection] = useState(reflectionValue);
  if (block.type === 'checkpoint') { const submitted = !!checkpointResult; return <div className="space-y-5"><p className="text-lg font-semibold leading-8 text-base-content">{block.prompt}</p><div className="grid gap-3">{block.options.map((option) => { const selectedOption = selected === option; const correctOption = submitted && option === block.correctAnswer; const wrongSelected = submitted && selectedOption && !correctOption; return <button key={option} type="button" disabled={submitted} onClick={() => setSelected(option)} className={`rounded-2xl border p-4 text-left text-sm transition ${correctOption ? 'border-success/50 bg-success/10' : wrongSelected ? 'border-error/50 bg-error/10' : selectedOption ? 'border-primary bg-primary/5' : 'border-base-300 bg-base-100 hover:border-primary/35'}`}><span className="flex items-center justify-between gap-3"><span>{option}</span>{correctOption ? <CheckCircleIcon className="h-5 w-5 text-success" /> : wrongSelected ? <XCircleIcon className="h-5 w-5 text-error" /> : null}</span></button>; })}</div>{!submitted && <button type="button" disabled={!selected} onClick={() => onCheckpoint(selected, selected === block.correctAnswer)} className="btn btn-primary w-full sm:w-auto">Check my thinking</button>}{submitted && <div className={`rounded-2xl p-4 ${checkpointResult?.correct ? 'bg-success/10' : 'bg-warning/10'}`}><div className="mb-1 font-semibold">{checkpointResult?.correct ? 'Yes — that distinction holds.' : 'Use the correction, then retrieve it again.'}</div><p className="text-sm leading-6 text-base-content/75">{block.explanation}</p></div>}</div>; }
  if (block.type === 'interactive') return <div className="space-y-6"><p className="leading-7 text-base-content/75">{block.body}</p><LessonVisual visual={block.visual} />{block.challenge && <div className="flex gap-3 rounded-2xl border border-primary/15 bg-primary/5 p-4"><LightBulbIcon className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><p className="text-sm leading-6"><strong>Try this:</strong> {block.challenge}</p></div>}</div>;
  if (block.type === 'youtube') { const embedUrl = getYouTubeEmbedUrl(block.url, block.startSeconds); return <div className="space-y-5"><p className="leading-7 text-base-content/75">{block.why}</p>{embedUrl && <div className="aspect-video overflow-hidden rounded-2xl border border-base-300 bg-black"><iframe src={embedUrl} title={block.title} className="h-full w-full" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div>}<a href={block.url} target="_blank" rel="noreferrer" className="btn btn-ghost btn-sm"><ArrowTopRightOnSquareIcon className="h-4 w-4" />Open on YouTube{block.channel ? ` · ${block.channel}` : ''}</a></div>; }
  if (block.type === 'reflection') return <div className="space-y-4"><p className="text-lg font-semibold leading-8">{block.prompt}</p><textarea value={reflection} onChange={(event) => setReflection(event.target.value)} onBlur={() => onReflection(reflection.trim())} placeholder={block.placeholder} className="textarea textarea-bordered min-h-32 w-full text-base leading-7" /><p className="text-xs text-base-content/55">Saved locally on this device when you leave the field.</p></div>;
  if (block.type === 'takeaways') return <div className="space-y-3">{block.items.map((item,index) => <div key={item} className="flex gap-3 rounded-2xl bg-base-200/60 p-4"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">{index+1}</div><p className="leading-6">{item}</p></div>)}</div>;
  return <div className="space-y-5"><p className="text-lg leading-8 text-base-content/80">{block.body}</p>{block.bullets && <div className="grid gap-3 sm:grid-cols-3">{block.bullets.map((item) => <div key={item} className="rounded-2xl bg-base-200/60 p-4 text-sm leading-6">{item}</div>)}</div>}{block.visual && <LessonVisual visual={block.visual} />}</div>;
}
