import { useEffect, useMemo, useState } from 'react';

export default function OrbitLab() {
  const [mass, setMass] = useState(1); const [radius, setRadius] = useState(1); const [speedRatio, setSpeedRatio] = useState(1); const [phase, setPhase] = useState(0); const [playing, setPlaying] = useState(false);
  const circularSpeed = Math.sqrt(mass / radius); const actualSpeed = circularSpeed * speedRatio; const escapeRatio = Math.sqrt(2);
  const state = speedRatio < 0.72 ? 'falling inward' : speedRatio < 0.95 ? 'elliptical orbit' : speedRatio <= 1.05 ? 'near-circular orbit' : speedRatio < escapeRatio ? 'wide elliptical orbit' : 'escape trajectory';
  const eccentricity = Math.min(0.82, Math.abs(1 - speedRatio) * 1.6); const semiMajor = 30 + Math.max(0, speedRatio - 1) * 13; const semiMinor = semiMajor * Math.sqrt(Math.max(0.18, 1 - eccentricity ** 2)); const angle = phase * Math.PI * 2; const orbiting = speedRatio < escapeRatio;
  const object = useMemo(() => { if (orbiting) return { x: 50 + Math.cos(angle) * semiMajor, y: 50 + Math.sin(angle) * semiMinor }; const distance = 18 + phase * 65; return { x: 50 + Math.cos(phase * 1.1) * distance, y: 50 + Math.sin(phase * 1.1) * distance * 0.55 }; }, [angle, orbiting, phase, semiMajor, semiMinor]);
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setPhase((value) => (value + 0.006 * Math.max(0.45, actualSpeed)) % 1), 24); return () => window.clearInterval(timer); }, [playing, actualSpeed]);
  return <div className="min-w-0 max-w-full space-y-5 overflow-x-hidden">
    <div className="rounded-3xl bg-slate-950 p-4 sm:p-6"><svg viewBox="0 0 100 100" className="h-72 w-full" role="img" aria-label={`Object in a ${state}`}><defs><radialGradient id="starGlow"><stop offset="0%" stopColor="#fff7c2" /><stop offset="45%" stopColor="#fbbf24" /><stop offset="100%" stopColor="#f97316" /></radialGradient></defs>{orbiting ? <ellipse cx="50" cy="50" rx={semiMajor} ry={semiMinor} fill="none" className="stroke-cyan-300/45" strokeWidth="0.8" strokeDasharray="2 1" /> : <path d="M50 50 Q70 35 96 55" fill="none" className="stroke-cyan-300/45" strokeWidth="0.8" strokeDasharray="2 1" />}<circle cx="50" cy="50" r={7 + mass * 1.2} fill="url(#starGlow)" /><circle cx={object.x} cy={object.y} r="3" className="fill-white" /><line x1={object.x} y1={object.y} x2={object.x - Math.sin(angle) * 10 * speedRatio} y2={object.y + Math.cos(angle) * 10 * speedRatio} className="stroke-fuchsia-300" strokeWidth="1" /><line x1={object.x} y1={object.y} x2={object.x + (50 - object.x) * 0.22} y2={object.y + (50 - object.y) * 0.22} className="stroke-amber-300" strokeWidth="1" /><text x="4" y="8" className="fill-fuchsia-300 text-[3px]">sideways velocity</text><text x="4" y="14" className="fill-amber-300 text-[3px]">gravity inward</text></svg></div>
    <div className="lab-grid lab-grid-medium"><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>Central mass</span><span>{mass.toFixed(1)}×</span></span><input className="range range-primary range-sm" type="range" min="0.5" max="3" step="0.1" value={mass} onChange={(event) => setMass(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>Starting radius</span><span>{radius.toFixed(1)}×</span></span><input className="range range-secondary range-sm" type="range" min="0.6" max="2.2" step="0.1" value={radius} onChange={(event) => setRadius(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>Sideways speed</span><span>{speedRatio.toFixed(2)}× circular</span></span><input className="range range-accent range-sm" type="range" min="0.35" max="1.65" step="0.02" value={speedRatio} onChange={(event) => { setSpeedRatio(Number(event.target.value)); setPhase(0); }} /></label></div>
    <div className="lab-grid lab-grid-compact"><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Motion state</div><div className="mt-1 font-black capitalize">{state}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Circular speed</div><div className="mt-1 font-black">{circularSpeed.toFixed(2)}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Actual speed</div><div className="mt-1 font-black">{actualSpeed.toFixed(2)}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Escape threshold</div><div className="mt-1 font-black">{escapeRatio.toFixed(2)}×</div></div></div>
    <div className="flex flex-wrap gap-2"><button type="button" className="btn btn-primary btn-sm" onClick={() => setPlaying((value) => !value)}>{playing ? 'Pause' : 'Animate orbit'}</button><button type="button" className="btn btn-outline btn-sm" onClick={() => setSpeedRatio(1)}>Circular speed</button><button type="button" className="btn btn-outline btn-sm" onClick={() => setSpeedRatio(0.62)}>Too slow</button><button type="button" className="btn btn-outline btn-sm" onClick={() => setSpeedRatio(1.48)}>Escape</button></div>
    <p className="text-xs leading-5 text-base-content/60">This is a qualitative two-body teaching model, not a numerical orbital integrator. Real trajectories depend on direction, full initial conditions, other bodies, relativity, and collisions.</p>
  </div>;
}
