import { useMemo, useState } from 'react';

export default function PredatorPreyLab() {
  const [preyGrowth, setPreyGrowth] = useState(1.05); const [predation, setPredation] = useState(0.018); const [predatorDecline, setPredatorDecline] = useState(0.72); const [predatorGain, setPredatorGain] = useState(0.012); const [initialPrey, setInitialPrey] = useState(55); const [initialPredators, setInitialPredators] = useState(18);
  const series = useMemo(() => { let prey = initialPrey; let predators = initialPredators; const points: { prey: number; predators: number }[] = []; for (let index = 0; index < 220; index += 1) { points.push({ prey, predators }); const dt = 0.035; const preyChange = preyGrowth * prey - predation * prey * predators; const predatorChange = predatorGain * prey * predators - predatorDecline * predators; prey = Math.max(0.1, Math.min(220, prey + preyChange * dt)); predators = Math.max(0.1, Math.min(220, predators + predatorChange * dt)); } return points; }, [initialPredators, initialPrey, predation, predatorDecline, predatorGain, preyGrowth]);
  const maximum = Math.max(...series.flatMap((point) => [point.prey, point.predators]), 1); const preyPoints = series.map((point, index) => `${4 + index / (series.length - 1) * 92},${94 - point.prey / maximum * 84}`).join(' '); const predatorPoints = series.map((point, index) => `${4 + index / (series.length - 1) * 92},${94 - point.predators / maximum * 84}`).join(' ');
  const peakPrey = Math.max(...series.map((point) => point.prey)); const peakPredators = Math.max(...series.map((point) => point.predators)); const preyPeakIndex = series.findIndex((point) => point.prey === peakPrey); const predatorPeakIndex = series.findIndex((point) => point.predators === peakPredators);
  return <div className="space-y-5">
    <div className="rounded-3xl bg-slate-950 p-4 sm:p-6"><svg viewBox="0 0 100 100" className="h-64 w-full" role="img" aria-label="Predator and prey populations changing through time">{[25, 50, 75].map((value) => <line key={value} x1="4" x2="96" y1={94 - value * 0.84} y2={94 - value * 0.84} className="stroke-slate-800" strokeWidth="0.4" />)}<polyline points={preyPoints} fill="none" className="stroke-emerald-300" strokeWidth="2" /><polyline points={predatorPoints} fill="none" className="stroke-fuchsia-300" strokeWidth="2" /><text x="68" y="10" className="fill-emerald-300 text-[4px]">prey</text><text x="68" y="16" className="fill-fuchsia-300 text-[4px]">predators</text><text x="76" y="98" className="fill-slate-500 text-[3px]">time →</text></svg></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Prey reproduction</span><span>{preyGrowth.toFixed(2)}</span></span><input className="range range-success range-sm" type="range" min="0.4" max="1.6" step="0.05" value={preyGrowth} onChange={(event) => setPreyGrowth(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Predation pressure</span><span>{predation.toFixed(3)}</span></span><input className="range range-secondary range-sm" type="range" min="0.005" max="0.04" step="0.001" value={predation} onChange={(event) => setPredation(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Predator decline</span><span>{predatorDecline.toFixed(2)}</span></span><input className="range range-warning range-sm" type="range" min="0.2" max="1.4" step="0.05" value={predatorDecline} onChange={(event) => setPredatorDecline(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Food → predator growth</span><span>{predatorGain.toFixed(3)}</span></span><input className="range range-accent range-sm" type="range" min="0.004" max="0.03" step="0.001" value={predatorGain} onChange={(event) => setPredatorGain(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Starting prey</span><span>{initialPrey}</span></span><input className="range range-primary range-sm" type="range" min="10" max="100" value={initialPrey} onChange={(event) => setInitialPrey(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-xs font-medium"><span>Starting predators</span><span>{initialPredators}</span></span><input className="range range-info range-sm" type="range" min="2" max="50" value={initialPredators} onChange={(event) => setInitialPredators(Number(event.target.value))} /></label></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Peak prey</div><div className="mt-1 text-xl font-black">{peakPrey.toFixed(0)}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Peak predators</div><div className="mt-1 text-xl font-black">{peakPredators.toFixed(0)}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Peak order</div><div className="mt-1 font-black">{preyPeakIndex < predatorPeakIndex ? 'Prey first' : 'Predators first'}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Lag</div><div className="mt-1 font-black">{Math.abs(predatorPeakIndex - preyPeakIndex)} steps</div></div></div>
    <div className="flex flex-wrap gap-2"><button type="button" className="btn btn-outline btn-sm" onClick={() => { setPreyGrowth(1.05); setPredation(0.018); setPredatorDecline(0.72); setPredatorGain(0.012); }}>Oscillating pair</button><button type="button" className="btn btn-outline btn-sm" onClick={() => { setPredation(0.035); setPredatorGain(0.02); }}>Strong coupling</button><button type="button" className="btn btn-outline btn-sm" onClick={() => { setPredatorDecline(1.25); setPredatorGain(0.006); }}>Predator stress</button></div>
    <p className="text-xs leading-5 text-base-content/60">This is a bounded Lotka–Volterra-style toy model. Real ecosystems include carrying capacity, many species, seasons, migration, age structure, disease, and changing habitats.</p>
  </div>;
}
