import { useMemo, useState } from 'react';
const initial=()=>Array.from({length:41},(_,i)=>Math.exp(-((i-12)**2)/50));const normalize=(v:number[])=>{const t=v.reduce((s,x)=>s+x,0)||1;return v.map((x)=>x/t);};
export default function SelectionLab(){
 const [distribution,setDistribution]=useState(()=>normalize(initial()));const [optimum,setOptimum]=useState(72);const [strength,setStrength]=useState(0.65);const [mixing,setMixing]=useState(0.16);const [generation,setGeneration]=useState(0);
 const evolve=(source:number[])=>{const selected=source.map((value,i)=>{const trait=i*2.5;const width=34-strength*24;return value*Math.exp(-((trait-optimum)**2)/(2*width**2));});return normalize(selected.map((value,i)=>value*(1-mixing)+mixing*((selected[i-1]||0)+value+(selected[i+1]||0))/3));};
 const advance=(count:number)=>{setDistribution((current)=>{let next=current;for(let i=0;i<count;i+=1)next=evolve(next);return next;});setGeneration((value)=>value+count);};
 const stats=useMemo(()=>{const mean=distribution.reduce((s,v,i)=>s+v*i*2.5,0);const variance=distribution.reduce((s,v,i)=>s+v*((i*2.5-mean)**2),0);return{mean,spread:Math.sqrt(variance),max:Math.max(...distribution)};},[distribution]);
 return <div className="space-y-5"><div className="rounded-3xl bg-slate-950 p-4"><svg viewBox="0 0 100 62" className="h-60 w-full" role="img" aria-label="Trait distribution over generations"><line x1="2" x2="98" y1="56" y2="56" className="stroke-slate-600" />{distribution.map((v,i)=>{const h=(v/stats.max)*45;return <rect key={i} x={2+i*2.34} y={56-h} width="1.75" height={h} className="fill-cyan-300/80" />;})}<line x1={2+(optimum/100)*96} x2={2+(optimum/100)*96} y1="4" y2="56" className="stroke-fuchsia-300" strokeDasharray="2 1" /><text x={Math.min(80,2+(optimum/100)*96)} y="8" className="fill-fuchsia-300 text-[3px]">environment favors here</text></svg></div>
 <div className="grid gap-4 sm:grid-cols-3"><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>Favored trait</span><span>{optimum}</span></span><input className="range range-primary range-sm" type="range" min="10" max="90" value={optimum} onChange={(e)=>setOptimum(Number(e.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>Selection</span><span>{Math.round(strength*100)}%</span></span><input className="range range-secondary range-sm" type="range" min="0.1" max="1" step="0.05" value={strength} onChange={(e)=>setStrength(Number(e.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>Variation mixing</span><span>{Math.round(mixing*100)}%</span></span><input className="range range-accent range-sm" type="range" min="0" max="0.45" step="0.03" value={mixing} onChange={(e)=>setMixing(Number(e.target.value))} /></label></div>
 <div className="grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs">Generation</div><div className="text-2xl font-black">{generation}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs">Mean trait</div><div className="text-2xl font-black">{stats.mean.toFixed(1)}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs">Spread</div><div className="text-2xl font-black">{stats.spread.toFixed(1)}</div></div></div><div className="flex gap-2"><button className="btn btn-primary btn-sm" onClick={()=>advance(1)}>Next generation</button><button className="btn btn-secondary btn-sm" onClick={()=>advance(10)}>Run 10</button><button className="btn btn-ghost btn-sm" onClick={()=>{setDistribution(normalize(initial()));setGeneration(0);}}>Reset</button></div><p className="text-xs leading-5 text-base-content/60">Individuals do not move toward a target. Differential reproduction changes the population distribution across generations.</p></div>;
}
