import { useEffect, useMemo, useRef, useState } from 'react';

type WebkitWindow = Window & typeof globalThis & { webkitAudioContext?: typeof AudioContext };

export default function SoundWaveLab() {
  const [frequency, setFrequency] = useState(440); const [amplitude, setAmplitude] = useState(0.45); const [playing, setPlaying] = useState(false);
  const audioRef = useRef<{ ctx: AudioContext; oscillator: OscillatorNode; gain: GainNode } | null>(null);
  const points = useMemo(() => { const cycles = 1.5 + ((frequency - 110) / 770) * 5.5; return Array.from({ length: 121 }, (_, index) => { const x = (index / 120) * 100; const y = 50 - Math.sin((index / 120) * Math.PI * 2 * cycles) * amplitude * 42; return `${x},${y}`; }).join(' '); }, [frequency, amplitude]);
  const stop = () => { const current = audioRef.current; if (current) { try { current.oscillator.stop(); } catch { /* already stopped */ } void current.ctx.close(); audioRef.current = null; } setPlaying(false); };
  const toggle = () => { if (playing) { stop(); return; } const AudioCtx = window.AudioContext || (window as WebkitWindow).webkitAudioContext; if (!AudioCtx) return; const ctx = new AudioCtx(); const oscillator = ctx.createOscillator(); const gain = ctx.createGain(); oscillator.type = 'sine'; oscillator.frequency.value = frequency; gain.gain.value = Math.min(0.18, amplitude * 0.18); oscillator.connect(gain); gain.connect(ctx.destination); oscillator.start(); audioRef.current = { ctx, oscillator, gain }; setPlaying(true); };
  useEffect(() => { if (audioRef.current) { audioRef.current.oscillator.frequency.setTargetAtTime(frequency, audioRef.current.ctx.currentTime, 0.03); audioRef.current.gain.gain.setTargetAtTime(Math.min(0.18, amplitude * 0.18), audioRef.current.ctx.currentTime, 0.03); } }, [frequency, amplitude]);
  useEffect(() => () => { const current = audioRef.current; if (current) { try { current.oscillator.stop(); } catch { /* already stopped */ } void current.ctx.close(); } }, []);
  return <div className="min-w-0 max-w-full space-y-5 overflow-x-hidden"><div className="rounded-3xl bg-slate-950 p-4 sm:p-6"><svg viewBox="0 0 100 100" className="h-44 w-full" role="img" aria-label="Interactive sine waveform"><line x1="0" x2="100" y1="50" y2="50" stroke="currentColor" className="text-slate-700" strokeWidth="0.5" /><polyline points={points} fill="none" stroke="currentColor" className="text-cyan-300" strokeWidth="2" strokeLinecap="round" /></svg></div><div className="lab-grid lab-grid-wide"><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>Frequency</span><span>{frequency} Hz</span></span><input className="range range-primary range-sm" type="range" min="110" max="880" step="10" value={frequency} onChange={(event) => setFrequency(Number(event.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm font-medium"><span>Amplitude</span><span>{Math.round(amplitude*100)}%</span></span><input className="range range-secondary range-sm" type="range" min="0.1" max="1" step="0.05" value={amplitude} onChange={(event) => setAmplitude(Number(event.target.value))} /></label></div><button type="button" onClick={toggle} className={`btn ${playing ? 'btn-error' : 'btn-primary'} w-full sm:w-auto`}>{playing ? 'Stop tone' : 'Hear tone'}</button><p className="text-xs leading-5 text-base-content/60">Keep volume comfortable. The drawing compresses frequency into visible cycles; it is for intuition rather than oscilloscope measurement.</p></div>;
}
