import { useMemo, useState } from 'react';
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
export default function SupplyDemandLab(){
 const [demandShift,setDemandShift]=useState(0);const [supplyShift,setSupplyShift]=useState(0);const [marketPrice,setMarketPrice]=useState(45);
 const equilibrium=useMemo(()=>{const price=clamp((90+demandShift-supplyShift)/2,5,95);return{price,quantity:clamp(100+demandShift-price,0,120)};},[demandShift,supplyShift]);
 const demanded=clamp(100+demandShift-marketPrice,0,120);const supplied=clamp(10+supplyShift+marketPrice,0,120);const gap=demanded-supplied;const x=(q:number)=>8+q/120*84;const y=(p:number)=>90-p/100*80;
 return <div className="space-y-5"><div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-3xl bg-slate-950 p-4"><svg viewBox="0 0 100 100" className="h-64 w-full" role="img" aria-label="Supply and demand curves"><line x1="8" x2="92" y1="90" y2="90" className="stroke-slate-500" /><line x1="8" x2="8" y1="10" y2="90" className="stroke-slate-500" /><line x1={x(clamp(100+demandShift,0,120))} y1={y(0)} x2={x(clamp(demandShift,0,120))} y2={y(100)} className="stroke-cyan-300" strokeWidth="2" /><line x1={x(clamp(10+supplyShift,0,120))} y1={y(0)} x2={x(clamp(110+supplyShift,0,120))} y2={y(100)} className="stroke-fuchsia-300" strokeWidth="2" /><line x1="8" x2="92" y1={y(marketPrice)} y2={y(marketPrice)} className="stroke-amber-300" strokeDasharray="2 1" /><circle cx={x(equilibrium.quantity)} cy={y(equilibrium.price)} r="2.4" className="fill-white" /><text x="72" y="18" className="fill-cyan-300 text-[4px]">demand</text><text x="72" y="78" className="fill-fuchsia-300 text-[4px]">supply</text></svg></div><div className="space-y-3"><div className="rounded-3xl border border-primary/20 bg-primary/5 p-5 text-center"><div className="text-xs font-bold uppercase text-primary">Clearing point</div><div className="mt-2 text-4xl font-black">{equilibrium.price.toFixed(0)}</div><div className="text-sm">≈ {equilibrium.quantity.toFixed(0)} units</div></div><div className={`rounded-3xl p-5 text-center ${Math.abs(gap)<2?'bg-success/10':gap>0?'bg-warning/15':'bg-info/10'}`}><div className="text-xs font-bold uppercase">At chosen price</div><div className="mt-2 text-3xl font-black">{Math.abs(gap).toFixed(0)}</div><div className="text-sm">{Math.abs(gap)<2?'roughly clears':gap>0?'unit shortage':'unit surplus'}</div></div></div></div>
 <div className="grid gap-4 sm:grid-cols-3"><label className="space-y-2"><span className="flex justify-between text-sm"><span>Demand shift</span><span>{demandShift}</span></span><input className="range range-primary range-sm" type="range" min="-30" max="30" value={demandShift} onChange={(e)=>setDemandShift(Number(e.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm"><span>Supply shift</span><span>{supplyShift}</span></span><input className="range range-secondary range-sm" type="range" min="-30" max="30" value={supplyShift} onChange={(e)=>setSupplyShift(Number(e.target.value))} /></label><label className="space-y-2"><span className="flex justify-between text-sm"><span>Chosen price</span><span>{marketPrice}</span></span><input className="range range-accent range-sm" type="range" min="5" max="95" value={marketPrice} onChange={(e)=>setMarketPrice(Number(e.target.value))} /></label></div>
 <div className="flex flex-wrap gap-2"><button className="btn btn-outline btn-sm" onClick={()=>{setDemandShift(20);setSupplyShift(0);}}>Demand rises</button><button className="btn btn-outline btn-sm" onClick={()=>{setDemandShift(0);setSupplyShift(-20);}}>Supply disruption</button><button className="btn btn-outline btn-sm" onClick={()=>{setDemandShift(0);setSupplyShift(20);}}>Productivity gain</button><button className="btn btn-ghost btn-sm" onClick={()=>{setDemandShift(0);setSupplyShift(0);setMarketPrice(45);}}>Reset</button></div><p className="text-xs leading-5 text-base-content/60">Linear teaching curves, not a forecast. Real markets include institutions, strategy, inventories, time, and bargaining power.</p></div>;
}
