import { useMemo, useState } from 'react';

type Rule = 'AND' | 'OR' | 'XOR' | 'IMPLIES' | 'COMPOSITE';
const evaluate = (rule: Rule, a: boolean, b: boolean, c: boolean) => rule === 'AND' ? a && b : rule === 'OR' ? a || b : rule === 'XOR' ? a !== b : rule === 'IMPLIES' ? !a || b : (a && b) || !c;
const labels: Record<Rule, string> = { AND: 'A AND B', OR: 'A OR B', XOR: 'A XOR B', IMPLIES: 'A → B', COMPOSITE: '(A AND B) OR NOT C' };

export default function TruthTableLab() {
  const [rule, setRule] = useState<Rule>('IMPLIES'); const [a, setA] = useState(true); const [b, setB] = useState(false); const [c, setC] = useState(true);
  const rows = useMemo(() => Array.from({ length: rule === 'COMPOSITE' ? 8 : 4 }, (_, index) => { const rowA = Boolean(index & (rule === 'COMPOSITE' ? 4 : 2)); const rowB = Boolean(index & (rule === 'COMPOSITE' ? 2 : 1)); const rowC = rule === 'COMPOSITE' ? Boolean(index & 1) : false; return { a: rowA, b: rowB, c: rowC, result: evaluate(rule, rowA, rowB, rowC) }; }), [rule]);
  const current = evaluate(rule, a, b, c); const matchingIndex = rows.findIndex((row) => row.a === a && row.b === b && (rule !== 'COMPOSITE' || row.c === c)); const trueRows = rows.filter((row) => row.result).length;
  return <div className="space-y-5">
    <div className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl bg-slate-950 p-5 text-center"><div className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-300">Current rule</div><div className="mt-3 text-2xl font-black text-white">{labels[rule]}</div><div className="mt-7 flex items-center justify-center gap-3"><div className={`rounded-2xl px-5 py-4 text-xl font-black ${a ? 'bg-emerald-400 text-slate-950' : 'bg-slate-800 text-slate-400'}`}>A {a ? 'T' : 'F'}</div><div className="text-slate-500">+</div><div className={`rounded-2xl px-5 py-4 text-xl font-black ${b ? 'bg-fuchsia-400 text-slate-950' : 'bg-slate-800 text-slate-400'}`}>B {b ? 'T' : 'F'}</div>{rule === 'COMPOSITE' ? <><div className="text-slate-500">+</div><div className={`rounded-2xl px-5 py-4 text-xl font-black ${c ? 'bg-amber-300 text-slate-950' : 'bg-slate-800 text-slate-400'}`}>C {c ? 'T' : 'F'}</div></> : null}</div><div className="my-5 text-slate-500">↓</div><div className={`mx-auto max-w-xs rounded-3xl p-6 text-4xl font-black ${current ? 'bg-success text-success-content' : 'bg-error text-error-content'}`}>{current ? 'TRUE' : 'FALSE'}</div></div><div className="overflow-x-auto rounded-3xl border border-base-300 bg-base-100 p-4 sm:p-6"><table className="table table-sm"><thead><tr><th>A</th><th>B</th>{rule === 'COMPOSITE' ? <th>C</th> : null}<th>{labels[rule]}</th></tr></thead><tbody>{rows.map((row, index) => <tr key={index} className={index === matchingIndex ? 'bg-primary/10 font-bold' : ''}><td>{row.a ? 'T' : 'F'}</td><td>{row.b ? 'T' : 'F'}</td>{rule === 'COMPOSITE' ? <td>{row.c ? 'T' : 'F'}</td> : null}<td><span className={`badge badge-sm ${row.result ? 'badge-success' : 'badge-error'}`}>{row.result ? 'T' : 'F'}</span></td></tr>)}</tbody></table></div></div>
    <div className="grid gap-4 sm:grid-cols-[1fr_auto]"><label className="space-y-2"><span className="text-sm font-medium">Logical rule</span><select className="select select-bordered w-full" value={rule} onChange={(event) => setRule(event.target.value as Rule)}><option value="AND">A AND B</option><option value="OR">A OR B</option><option value="XOR">A XOR B</option><option value="IMPLIES">A → B</option><option value="COMPOSITE">(A AND B) OR NOT C</option></select></label><div className="flex flex-wrap items-end gap-2"><button type="button" className={`btn btn-sm ${a ? 'btn-success' : 'btn-ghost'}`} onClick={() => setA((value) => !value)}>A = {a ? 'T' : 'F'}</button><button type="button" className={`btn btn-sm ${b ? 'btn-secondary' : 'btn-ghost'}`} onClick={() => setB((value) => !value)}>B = {b ? 'T' : 'F'}</button>{rule === 'COMPOSITE' ? <button type="button" className={`btn btn-sm ${c ? 'btn-warning' : 'btn-ghost'}`} onClick={() => setC((value) => !value)}>C = {c ? 'T' : 'F'}</button> : null}</div></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">Possible rows</div><div className="mt-1 text-xl font-black">{rows.length}</div></div><div className="rounded-2xl bg-base-200/70 p-3"><div className="text-xs text-base-content/55">True rows</div><div className="mt-1 text-xl font-black">{trueRows}</div></div><div className="col-span-2 rounded-2xl bg-base-200/70 p-3 sm:col-span-1"><div className="text-xs text-base-content/55">False rows</div><div className="mt-1 text-xl font-black">{rows.length - trueRows}</div></div></div>
    <p className="text-xs leading-5 text-base-content/60">A truth table evaluates structure, not whether the input statements match reality. A valid implication can contain false premises; logic and factual truth are different questions.</p>
  </div>;
}
