export const cs = {
  // General
  appName: "Aplikace Kvíz",
  
  // Navigation
  nav: {
    home: "Domů",
    categories: "Kategorie",
    mistakes: "Chyby",
    settings: "Nastavení",
    achievements: "Úspěchy",
    about: "O nás",
    contact: "Kontakt",
    share: "Sdílet",
    dashboard: "Nástěnka",
    questions: "Otázky",
    chat: "AI Chat",
  },
  
  // Screens
  homeScreen: {
    welcome: "Vítejte v Kvízu!",
    enterName: "Zadejte své jméno pro začátek",
    placeholder: "Vaše jméno",
    letsGo: "Pojďme na to!",
    subtitle: "Otestujte své znalosti a naučte se něco nového",
    or: "Nebo",
    importProgress: "Importovat Pokrok",
    welcomeBack: "Vítejte zpět",
    readyToLearn: "Jste připraveni pokračovat ve své výuce?",
    toReview: "K Opakování",
    categories: "Kategorie",
    continueLearning: "Pokračovat ve Výuce",
    startLearning: "Začít Výuku",
    namePlaceholder: "Zadejte své jméno",
  },
  dashboard: {
    title: "Nástěnka",
    welcome: "Vítejte",
    subtitle: "Pokračujte ve své výuce",
    categories: "Kategorie",
    questions: "Otázky",
    toReview: "K Opakování",
    learningPath: "Výuková Cesta",
    browseAll: "Procházet vše",
    playAll: "Hrát Všechny Otázky",
    playAllDesc: "Otestujte své znalosti ve všech kategoriích",
    practice: "Cvičit",
    achievements: "Úspěchy",
    achievementsDesc: "Sledujte svůj pokrok a milníky",
    reviewMistakes: "Zopakovat Chyby",
    questionsToPractice: "otázek k procvičení",
    communityTools: "Komunita a Nástroje",
    aiAssistant: "AI Asistent",
    aiAssistantDesc: "Získejte pomoc s těžkými otázkami",
    customQuestions: "Vlastní Otázky",
    customQuestionsDesc: "Vytvářejte a spravujte svůj vlastní obsah",
  },
  categoriesScreen: {
    title: "Kategorie",
  },
  categoryScreen: {
    startQuiz: "Začít Kvíz",
    categoryNotFound: "Kategorie nenalezena",
  },
  quizScreen: {
    title: "Kvíz",
    next: "Další",
    submit: "Odeslat",
    finishQuiz: "Dokončit Kvíz",
    understood: "Rozumím",
    currentStreak: "Aktuální Série",
    bestStreak: "Nejlepší Série",
    question: "Otázka",
    showExplanation: "Zobrazit Vysvětlení",
    continueStreak: "Pokračovat v Sérii",
    loading: "Načítání...",
    unsupportedQuestionType: "Nepodporovaný typ otázky",
  },
  resultsScreen: {
    title: "Výsledky",
    score: "Vaše Skóre",
    correct: "Správně",
    incorrect: "Nesprávně",
    playAgain: "Hrát Znovu",
    backToCategories: "Zpět na Kategorie",
    streakOver: "Série Skončila!",
    questionsAnsweredCorrectly: "Otázky zodpovězené správně",
    newPersonalBest: "Nový osobní rekord!",
    personalBest: "Osobní Rekord",
    tryAgain: "Zkusit Znovu",
    explanation: "Vysvětlení",
    levelComplete: "Úroveň {{level}} Dokončena",
    greatJob: "Výborně! Zvládli jste tuto úroveň.",
    keepPracticing: "Pokračujte v procvičování pro zlepšení svého skóre!",
    incorrectAnswers: "Nesprávné Odpovědi: {{count}}",
    correctAnswers: "Správné Odpovědi: {{count}}",
    continue: "Pokračovat",
    reviewMistakes: "Zopakovat Chyby",
  },
  achievementsScreen: {
    title: "Úspěchy",
    points: "Body",
    correctAnswers: "Správné Odpovědi",
    completed: "Dokončeno",
    performanceByCategory: "Výkon podle Kategorie",
    questionsCount: "{{completed}}/{{total}} Otázek",
    accuracy: "{{accuracy}}% Správně",
    noPerformance: "Dokončete kvízy pro zobrazení svého výkonu!",
    practiceMistakes: "Cvičit Chyby ({{count}})",
    unlocked: "Odemčeno",
    progress: "Pokrok",
  },
  achievements: {
    firstSteps: {
      title: "První Kroky",
      description: "Dokončete svou první kvízovou otázku"
    },
    quizMaster: {
      title: "Mistr Kvízu",
      description: "Odpovězte správně na 50 otázek"
    },
    speedDemon: {
      title: "Rychlostní Ďábel",
      description: "Odpovězte na otázku za méně než 5 sekund"
    },
    streakChampion: {
      title: "Šampión Série",
      description: "Udržte 7denní sérii"
    },
    categoryConqueror: {
      title: "Dobyvatel Kategorií",
      description: "Dokončete všechny otázky v jedné kategorii"
    },
    perfectScore: {
      title: "Perfektní Skóre",
      description: "Získejte 100% v kvízu s 10+ otázkami"
    },
    dedicatedLearner: {
      title: "Zasvěcený Student",
      description: "Dokončete 100 otázek"
    },
    mistakeMaster: {
      title: "Mistr Chyb",
      description: "Zopakujte a opravte 20 chyb"
    },
    wellRounded: {
      title: "Dobře Zaoblený",
      description: "Dokončete kvízy ve 3 různých kategoriích"
    }
  },
  achievementTiers: {
    bronze: "Bronz",
    silver: "Stříbro",
    gold: "Zlato",
    platinum: "Platina"
  },
  mistakesScreen: {
    title: "Moje Chyby",
    noMistakes: "Zatím jste neudělali žádné chyby. Pokračujte!",
    reviewMistakesInCategory: "Zopakujte si své chyby v {{category}}",
    score: "Skóre",
    categories: "Kategorie",
    total: "Celkem",
    practiceAllMistakes: "Cvičit Všechny Chyby",
    wrongAnswers: "Špatné Odpovědi",
  },
  settingsScreen: {
    title: "Nastavení",
    language: "Jazyk",
    theme: "Téma",
    sound: "Zvukové Efekty",
    about: "O nás",
    import: "Importovat Pokrok",
    export: "Exportovat Pokrok",
    contact: "Kontaktujte Nás",
    share: "Sdílet",
    reset: "Resetovat Pokrok",
    aiSettings: "AI Nastavení",
    aiGenerationSettings: "Nastavení Generování AI",
    progressSummary: "Shrnutí Pokroku",
    categories: "Kategorie",
    mistakes: "Chyby",
    lastUpdated: "Naposledy Aktualizováno",
    darkMode: "Tmavý Režim",
    lightMode: "Světlý Režim",
    soundOn: "Zapnuto",
    soundOff: "Vypnuto",
  },
  aboutScreen: {
    title: "O nás",
    aboutApp: "O Aplikaci",
    description1: "Tato aplikace vám pomáhá učit se a testovat své znalosti prostřednictvím interaktivních kvízů.",
    description2: "Sledujte svůj pokrok, zopakujte si své chyby a zlepšujte své dovednosti v průběhu času.",
    features: "Hlavní Funkce",
    feature1: "Interaktivní kvízy ve více kategoriích",
    feature2: "Sledování vašeho pokroku a úspěchů",
    feature3: "Opakování a procvičování chyb",
    feature4: "AI-poháněná pomoc pro těžké otázky",
    feature5: "Vytváření a správa vlastních otázek",
    contact: "Kontaktujte Nás",
    contactInfo: "Pokud máte nějaké dotazy nebo zpětnou vazbu, kontaktujte nás prosím na support@quizapp.com",
  },
  contactScreen: {
    title: "Kontaktujte Nás",
    getInTouch: "Spojte se s Námi",
    description: "Máte otázky nebo zpětnou vazbu? Rádi bychom o vás slyšeli!",
    name: "Jméno",
    email: "Email",
    message: "Zpráva",
    sendMessage: "Odeslat Zprávu",
    sending: "Odesílání...",
    successMessage: "Vaše zpráva byla úspěšně odeslána!",
    errorMessage: "Při odesílání vaší zprávy došlo k chybě. Prosím zkuste to znovu.",
  },
  shareScreen: {
    title: "Sdílet",
    inviteFriends: "Pozvat Přátele",
    helpGrow: "Pomozte nám růst sdílením aplikace s vašimi přáteli!",
    copyLink: "Kopírovat Odkaz",
    successTitle: "Úspěch!",
    successMessage: "Aplikace byla úspěšně sdílena přes {{method}}",
    errorTitle: "Chyba",
    errorMessage: "Nepodařilo se sdílet přes {{method}}. Prosím zkuste to znovu.",
    backToDashboard: "Zpět na Nástěnku",
  },
  chatScreen: {
    title: "AI Asistent",
    warning: "Varování: Klíč API Gemini není nastaven. Nastavte jej prosím v záložce AI v Otázkové Bance.",
    startConversation: "Začněte konverzaci!",
    prompt: "Položte otázku, nahrajte obrázek nebo vyberte kategorii pro kontext.",
    quizContext: "Kontext Kvízu:",
    noContext: "Žádný Kontext",
    myMistakes: "Moje Chyby",
    typeMessage: "Napište svou zprávu...",
    chatOptions: "Možnosti Chatu",
    clearHistory: "Vymazat Historii Chatu",
    startCall: "Zahájit Hlasový Hovor",
    sendMessage: "Odeslat zprávu",
    generatedImageAlt: "vygenerovaný obrázek",
    reviewMistakesPrompt: "Toto byl test, který jsem psal, a toto jsou všechny otázky, ve kterých jsem udělal chyby, nyní potřebuji vaši pomoc s opakováním a učením se z mých chyb",
    categoryHelpPrompt: "Toto jsou otázky z kategorie {{category}}. Prosím pomozte mi dozvědět se více o vybraných datech.",
  },
  difficultyScreen: {
    title: "Vyberte Obtížnost",
    noQuestions: "Pro tuto kategorii zatím nejsou k dispozici žádné otázky.",
    questionsAvailable: "dostupných otázek",
    startQuiz: "Začít Kvíz",
  },
  questionBankScreen: {
    title: "Otázková Banka",
    manual: "Ručně",
    aiMode: "AI Režim",
    addNew: "Přidat Novou",
    options: "Možnosti",
    import: "Importovat",
    export: "Exportovat",
    markdownSupport: "💡 Vysvětlení nyní podporují formátování Markdown pro formátovaný text, odkazy a seznamy",
    searchPlaceholder: "Hledat otázky...",
    selectAll: "Vybrat Vše",
    delete: "Smazat",
    edit: "Upravit",
    noQuestions: "Nebyly Nalezeny Žádné Otázky",
    noResults: "Žádné výsledky pro \"{{searchTerm}}\".",
    emptyBank: "Vaše otázková banka je prázdná.",
    addFirstQuestion: "Přidejte Svoji První Otázku",
    confirmDelete: {
      title: "Potvrdit Smazání",
      message: "Opravdu chcete smazat tuto otázku? Tuto akci nelze vrátit zpět.",
    },
    importModal: {
      importFailed: "Import se nezdařil. Opravte prosím následující problémy:",
      invalidJson: "Neplatný formát JSON. Zkontrolujte syntaktické chyby.",
    },
  },
  categories: {
    youtube_growth: {
      description: "Strategie pro růst vašeho YouTube kanálu",
    },
    youtube_monetization: {
      description: "Vydělávání peněz z vašeho YouTube obsahu",
    },
    youtube_content: {
      description: "Tipy pro vytváření poutavých videí",
    },
    youtube_analytics: {
      description: "Porozumění výkonu vašeho kanálu",
    },
  },
  difficultyDescriptions: {
    easy: "Základní koncepty a základní znalosti",
    medium: "Středně pokročilé koncepty a detailní porozumění",
    hard: "Pokročilé koncepty a hluboké znalosti",
  },
  categoryEmojiMapping: {
    title: "Mapování Emoji Kategorií",
    searchPlaceholder: "Hledat kategorie...",
    noCategoriesFound: "Nebyly nalezeny žádné kategorie",
  },
  liveCallComponent: {
    title: "Živý Hlasový Hovor",
    context: "Kontext:",
    contextDescription: "Využití vašeho pokroku v kvízu a chyb pro personalizovanou pomoc",
  },
  importQuestionsModal: {
    title: "Importovat Otázky",
    close: "Zavřít",
    importFormat: "Formát Importu",
    json: "JSON",
    csv: "CSV",
    dropFile: "Přetáhněte svůj {format} soubor sem nebo klikněte pro výběr",
    or: "NEBO",
    pasteRaw: "Vložit Surový Text",
    formatInfo: "Váš {format} soubor by měl mít následující strukturu:",
    cancel: "Zrušit",
    import: "Importovat",
  },
  aiGenerationTab: {
    title: "Generování AI",
    apiKey: {
      label: "Klíč API Gemini",
      placeholder: "Zadejte svůj klíč API Gemini",
      set: "Klíč API je nastaven",
      change: "Změnit Klíč",
      save: "Uložit",
      info: "Váš klíč je uložen pouze ve vašem prohlížeči. Získejte bezplatný klíč na",
    },
    prompt: {
      label: "Výzva",
      placeholder: "např: Vytvořte 10 otázek s výběrem odpovědí o Římské říši.",
      placeholderWithContext: "např: Vytvořte 10 otázek s výběrem odpovědí na základě obsahu {{context}} o starověké historii.",
      contextInfo: "AI analyzuje váš obsah {{context}} a generuje otázky na základě médií a vaší výzvy.",
    },
    mediaContext: {
      title: "Kontext pro Generování Otázek",
    },
    buttons: {
      generate: "Generovat Otázky",
      generating: "Generování...",
      assignEmojis: "Přiřadit Emojis Novým Kategoriím",
      enterEmoji: "Zadejte emoji pro tuto kategorii",
      back: "Zpět",
      saveAndAdd: "Uložit Emojis a Přidat Otázky",
      preview: "Vygenerované Otázky (Náhled)",
      discard: "Zahodit",
      nextAssign: "Další: Přiřadit Emojis",
      approveAndAdd: "Schválit a Přidat",
    },
    errors: {
      apiKeyMissing: "Prosím zadejte svůj klíč API Gemini. Bezplatný klíč můžete získat na ai.dev.",
      promptMissing: "Prosím zadejte výzvu pro generování otázek.",
      mediaContextMissing: "Prosím dokončete výběr kontextu médií nebo zvolte \"Žádný Kontext\".",
      generationFailed: "Nepodařilo se vygenerovat otázky. Prosím zkontrolujte svůj klíč API, výzvu a kontext médií.",
    },
  },
  sagaLearnScreen: {
    title: "SagaLearn",
    adventureAwaits: "Dobrodružství Čeká",
    adventureAwaitsDesc: "Nastavte scénu pro svůj epický příběh.",
    chooseWorld: "Vyberte Svět",
    selectHero: "Vyberte Hrdinu",
    customHero: "Vlastní Hrdina",
    customHeroDesc: "Definujte svého vlastního protagonistu od nuly.",
    customHeroPlaceholder: "např. Chytrý zloděj se srdcem ze zlata",
    selectKnowledgePack: "Vyberte Balíček Znalostí",
    optionalLearningQuest: "Volitelné: Přidejte Úkol Učení",
    justExploring: "Jen Prozkoumávám",
    justExploringDesc: "Čisté příběhové dobrodružství.",
    beginAdventure: "Začít Dobrodružství",
    craftingWorld: "Vytváření vašeho světa...",
    error: {
      apiKey: "Nejprve prosím nastavte svůj klíč API Gemini v Nastavení.",
      adventure: "Nepodařilo se spustit dobrodružství. Zkontrolujte prosím svůj klíč API a zkuste to znovu.",
      load: "Vaše uložené dobrodružství se zdá být poškozené. Musíme začít nové."
    },
    continuePrompt: {
      title: "Pokračovat ve vašem dobrodružství?",
      description: "Nedokončená cesta v režimu Volného Prozkoumávání na vás čeká.",
      continue: "Pokračovat",
      startOver: "Začít Nové Dobrodružství",
      loading: "Načítání vašeho dobrodružství..."
    },
    gameModeSelector: {
      title: "Vyberte Své Dobrodružství",
      description: "Vyberte herní režim pro zahájení vaší výukové cesty.",
      quizAdventure: "Dobrodružství Kvízu",
      quizAdventureDesc: "Strukturované, příběhem řízené dobrodružství, kde znalosti odemykají postup.",
      freeExploration: "Volné Prozkoumávání",
      freeExplorationDesc: "Otevřený svět, kde se můžete učit a objevovat ve vlastním tempu.",
      quizAdventureDetails: "Strukturované, příběhem řízené dobrodružství, kde znalosti odemykají postup.",
      freeExplorationDetails: "Otevřený svět, kde se můžete učit a objevovat ve vlastním tempu."
    },
    adventureConfigurator: {
      loading: "Vytváření vašeho světa...",
      error: "Nepodařilo se spustit dobrodružství. Zkontrolujte prosím svůj klíč API a zkuste to znovu.",
      adventureAwaits: "Dobrodružství Čeká",
      adventureAwaitsDesc: "Nastavte scénu pro svůj epický příběh.",
      chooseWorld: "Vyberte Svět",
      selectHero: "Vyberte Hrdinu",
      customHero: "Vlastní Hrdina",
      customHeroDesc: "Definujte svého vlastního protagonistu od nuly.",
      customHeroPlaceholder: "např. Chytrý zloděj se srdcem ze zlata",
      selectKnowledgePack: "Vyberte Balíček Znalostí",
      optionalLearningQuest: "Volitelné: Přidejte úkol na učení",
      justExploring: "Jen Prozkoumávání",
      justExploringDesc: "Čistě narrativní dobrodružství.",
      beginAdventure: "Začít Dobrodružství",
      selectOption: "Vyberte možnost"
    },
    customDropdown: {
      placeholder: "Vyberte možnost"
    },
    quizAdventureUI: {
      question: "Otázka",
      choices: "Volby",
      submit: "Odeslat",
      next: "Další",
      finish: "Dokončit Kvíz",
      loading: "Načítání další otázky...",
      explanation: "Vysvětlení",
      objective: "Cíl",
      survive: "Přežít",
      turnsRemaining: "Zbývající tahy: {{count}}",
      storyUnfolds: "Příběh se odvíjí...",
      victory: "Vítězství!",
      gameOver: "Konec hry",
      playAgain: "Hrát znovu",
      correct: "Správně!",
      incorrect: "Nesprávně!",
      generatingScene: "Generování scény...",
      openDashboard: "Otevřít Řídicí panel"
    },
    freeExplorationUI: {
      whatDoYouSay: "Co říkáš {{dialoguePartner}}?",
      whatDoYouDo: "Co děláš dál?",
      suggestions: "Návrhy",
      go: "Jít"
    }
  }
};